CREATE SCHEMA IF NOT EXISTS ordering;

DROP TABLE IF EXISTS ordering.orderItems;
DROP TABLE IF EXISTS ordering.orders;
DROP TABLE IF EXISTS ordering.paymentmethods;
DROP TABLE IF EXISTS ordering.buyers;
DROP TABLE IF EXISTS ordering.cardtypes;
DROP TABLE IF EXISTS ordering.orderstatus;
DROP TABLE IF EXISTS Catalog;
DROP TABLE IF EXISTS CatalogBrand;
DROP TABLE IF EXISTS CatalogType;

CREATE TABLE CatalogBrand (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Brand VARCHAR(100) NOT NULL
);

CREATE TABLE CatalogType (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Type VARCHAR(100) NOT NULL
);

CREATE TABLE Catalog (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(255),
    Price DECIMAL(18, 2) NOT NULL,
    PictureFileName VARCHAR(255),
    CatalogTypeId INT NOT NULL,
    CatalogBrandId INT NOT NULL,
    AvailableStock INT NOT NULL DEFAULT 0,
    RestockThreshold INT NOT NULL DEFAULT 0,
    MaxStockThreshold INT NOT NULL DEFAULT 0,
    OnReorder BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT FK_Catalog_CatalogBrand_CatalogBrandId FOREIGN KEY (CatalogBrandId) REFERENCES CatalogBrand (Id),
    CONSTRAINT FK_Catalog_CatalogType_CatalogTypeId FOREIGN KEY (CatalogTypeId) REFERENCES CatalogType (Id)
);

CREATE TABLE ordering.cardtypes (
    Id INT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL
);

CREATE TABLE ordering.orderstatus (
    Id INT PRIMARY KEY,
    Name VARCHAR(200) NOT NULL
);

CREATE TABLE ordering.buyers (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IdentityGuid VARCHAR(200) NOT NULL UNIQUE,
    Name VARCHAR(255)
);

CREATE TABLE ordering.paymentmethods (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Alias VARCHAR(200) NOT NULL,
    BuyerId INT NOT NULL,
    CardHolderName VARCHAR(200) NOT NULL,
    CardNumber VARCHAR(25) NOT NULL,
    CardTypeId INT NOT NULL,
    Expiration TIMESTAMP NOT NULL,
    CONSTRAINT FK_paymentmethods_buyers_BuyerId FOREIGN KEY (BuyerId) REFERENCES ordering.buyers (Id),
    CONSTRAINT FK_paymentmethods_cardtypes_CardTypeId FOREIGN KEY (CardTypeId) REFERENCES ordering.cardtypes (Id)
);

CREATE TABLE ordering.orders (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    BuyerId INT,
    Description VARCHAR(255),
    OrderDate TIMESTAMP NOT NULL,
    OrderStatusId INT NOT NULL,
    PaymentMethodId INT,
    Street VARCHAR(255),
    City VARCHAR(255),
    State VARCHAR(255),
    Country VARCHAR(255),
    ZipCode VARCHAR(255),
    CONSTRAINT FK_orders_buyers_BuyerId FOREIGN KEY (BuyerId) REFERENCES ordering.buyers (Id),
    CONSTRAINT FK_orders_orderstatus_OrderStatusId FOREIGN KEY (OrderStatusId) REFERENCES ordering.orderstatus (Id),
    CONSTRAINT FK_orders_paymentmethods_PaymentMethodId FOREIGN KEY (PaymentMethodId) REFERENCES ordering.paymentmethods (Id)
);

CREATE TABLE ordering.orderItems (
    Id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Discount DECIMAL(18, 2) NOT NULL,
    OrderId INT NOT NULL,
    PictureUrl VARCHAR(255),
    ProductId INT NOT NULL,
    ProductName VARCHAR(255) NOT NULL,
    UnitPrice DECIMAL(18, 2) NOT NULL,
    Units INT NOT NULL,
    CONSTRAINT FK_orderItems_orders_OrderId FOREIGN KEY (OrderId) REFERENCES ordering.orders (Id) ON DELETE CASCADE
);
